pipeline{
  agent {
    docker {
      image 'maven:3.9.6-eclipse-temurin-17'
    }
  }
  stages{
    stage('Git Checkout'){
      steps{
        checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Nehanilajkar/Jenkins-Projects.git']])
      }
    }
    stage('Docker build'){
      steps{
        sh 'docker build -t mvn:1 .'
      }
    }
  }
}
