pipeline {
  agent {
    docker {
      image 'maven-with-docker'
      args '-v /var/run/docker.sock:/var/run/docker.sock'
    }
  }
  stages {
    stage('Git Checkout') {
      steps {
        checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Nehanilajkar/Jenkins-Projects.git']])
      }
    }
    stage('Code Build') {
      steps {
        dir('Maven-test-project') {
          sh 'ls'
          sh 'mvn clean package'
        }
      }
    }
    stage('Docker Build') {
      steps {
        dir('Maven-test-project') {
          sh 'ls'
          sh 'docker build -t mvn:1 -f Dockerfile .'
        }
      }
    }
    stage('Docker Run') {
      steps {
        sh 'docker run -d -p 8000:8080 mvn:1'
      }
    }
  }
}
