pipeline{
  agent any
  stages{
    stage('Git Checkout'){
      steps{
        checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Nehanilajkar/Jenkins-Projects.git']])
      }
    }
    stage('code Build'){
      steps{
        sh 'cd Maven-test-project'
        sh 'ls'
        sh 'cd Maven-test-project && mvn clean package'
      }
    }
    stage('Docker build'){
      steps{
        sh 'ls'
        sh 'docker build -t mvn:1 -f Maven-test-project/Dockerfile .'
      }
    }
    stage('Docker run'){
      steps{
        sh 'docker run -d -p 8000:8080 mvn:1 '
      }
    }
  }
}
